### ISSUE TITLE
Support for automatically fetching the GitHub API endpoint

### ISSUE THREAD

**Issue by ponkio-o** [suzuki-shunsuke/github-comment#1489]
### Feature Overview

I would like to support getting the API endpoint from GitHub automatically.

Currently, we should set API endpoints (`ghe_base_url` / `ghe_graphql_endpoint`) to `^\.?github-comment\.ya?ml$` when running on GitHub Enterprise (Server/Cloud). 
But I think these endpoints can be automatically obtained from environment variables in GitHub Actions.

- `GITHUB_API_URL`
- `GITHUB_GRAPHQL_URL`

GitHub Enterprise Server
https://docs.github.com/en/enterprise-server@3.13/actions/writing-workflows/choosing-what-your-workflow-does/variables

GitHub Enterprise Cloud
https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/variables

GitHub (github.com)
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/variables

We confirmed that we can actually get our own domain using `GITHUB_API_URL` / `GITHUB_GRAPHQL_URL` on our GHES.

### Why is the feature needed?

We are using GitHub Enterprise Server, and `github-comment` in many repositories. Therefore, we should create `^\.?github-comment\.ya?ml$` file each repository to set API endpoint for GHES.

### Example Code

```console
$ 
```

Configuration

```yaml

```

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
Looks good.
I'll take a look.

## GitHub Enterprise Server

> GITHUB_API_URL | Returns the API URL. For example: http(s)://HOSTNAME/api/v3.
> GITHUB_GRAPHQL_URL | Returns the GraphQL API URL. For example: http(s)://HOSTNAME/api/graphql.

## GitHub Enterprise Cloud

> GITHUB_API_URL | Returns the API URL. For example: https://api.github.com.
> GITHUB_GRAPHQL_URL | Returns the GraphQL API URL. For example: https://api.github.com/graphql.


## GitHub (github.com)

> GITHUB_API_URL | Returns the API URL. For example: https://api.github.com.
> GITHUB_GRAPHQL_URL | Returns the GraphQL API URL. For example: https://api.github.com/graphql.

**Comment by suzuki-shunsuke** [comment]
📝 https://pkg.go.dev/github.com/google/go-github/v63/github#Client.WithEnterpriseURLs

> WithEnterpriseURLs returns a copy of the client configured to use the provided base and upload URLs.
> If the base URL does not have the suffix "/api/v3/", it will be added automatically.
> If the upload URL does not have the suffix "/api/uploads", it will be added automatically.
> Note that WithEnterpriseURLs is a convenience helper only; its behavior is equivalent to setting the BaseURL and UploadURL fields.
> Another important thing is that by default, the GitHub Enterprise URL format should be http(s)://[hostname]/api/v3/ or you will always receive the 406 status code.
> The upload URL format should be http(s)://[hostname]/api/uploads/.

**Comment by suzuki-shunsuke** [comment]
I've released the pre release version [v6.2.0-1](https://github.com/suzuki-shunsuke/github-comment/releases/tag/v6.2.0-1).

- https://github.com/suzuki-shunsuke/github-comment/pull/1490

Could you try v6.2.0-1 when you have time?

**Comment by ponkio-o** [comment]
@suzuki-shunsuke Thank you!!
I confirmed to run `github-comment post` command correctly without configuration file on GitHub Enterprise Server (and self-hosted runner).

**Comment by suzuki-shunsuke** [comment]
Thank you for confirming it!
v6.2.0 is out 🎉

https://github.com/suzuki-shunsuke/github-comment/releases/tag/v6.2.0
