### ISSUE TITLE
Support for Github Enterprise

### ISSUE THREAD

**Issue by mechastorm** [suzuki-shunsuke/github-comment#462]
Similar to https://github.com/suzuki-shunsuke/tfcmt/issues/300, is there a config in this tool to configure a custom Github base URL for GHE support?

Thank You!

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
Unlike tfcmt, github-comment doesn't support GitHub Enterprise yet.
We have to implement GitHub Enterprise Support.

**Comment by suzuki-shunsuke** [comment]
https://docs.github.com/en/enterprise-server@2.20/graphql/guides/forming-calls-with-graphql#the-graphql-endpoint
https://pkg.go.dev/github.com/shurcooL/githubv4#NewEnterpriseClient
https://pkg.go.dev/github.com/google/go-github/v44/github#NewEnterpriseClient

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/github-comment/pull/464

**Comment by suzuki-shunsuke** [comment]
Published a prerelease https://github.com/suzuki-shunsuke/github-comment/releases/tag/v4.2.0-0
Could you try to use this version?
I don't use GitHub Enterprise, so I can't confirm if it works well for GitHub Enterprise.
If it works well, I'll release v4.2.0.

**Comment by suzuki-shunsuke** [comment]
Please remove a slash.

AS IS: `https:///<ghe_url>/api/graphql`
TO BE: `https://<ghe_url>/api/graphql`

**Comment by mechastorm** [comment]
Thank you for catching that typo :cold_sweat:

I have run this now with the corrected config and can confirmed it is running as expected!

The command I run in Github Actions was

```
github-comment hide --config github-comment.yaml
```

So I think this updated binary is working as expected thanks to your updates.

**Comment by suzuki-shunsuke** [comment]
Thank you for your confirmation!
I've released https://github.com/suzuki-shunsuke/github-comment/releases/tag/v4.2.0
